@startuml
box client
Actor "Kafka Client"
end box

Control "System"

System --> Kroxylicious: main
create KafkaProxy
Kroxylicious --> KafkaProxy: startup

loop [for all unique virtual clusters bootstrap listeners]
  create NetFilter
  KafkaProxy --> NetFilter: new

  create KafkaProxyInitializer
  KafkaProxy --> KafkaProxyInitializer: new(netFilter)
  KafkaProxy --> KafkaProxyInitializer: startup

  create ServerChannel
  KafkaProxy --> ServerChannel: bind
end


"Kafka Client" --> ServerChannel: connect
create Channel
ServerChannel --> Channel: new
Channel -> KafkaProxyInitializer: initChannel

create KafkaProxyFrontendHandler
KafkaProxyInitializer --> KafkaProxyFrontendHandler: new

create KafkaProxyBackendHandler
KafkaProxyFrontendHandler --> KafkaProxyBackendHandler: new

"Kafka Client" -> KafkaProxyFrontendHandler: send(MetadataRequest)


@enduml
