@startuml

DownstreamCluster - UpstreamCluster

DownstreamCluster *--{ "n" DownstreamBroker
UpstreamCluster *--{ "n" UpstreamBroker

DownstreamBroker }-- EndPoint
DownstreamCluster --- FilterChain
UpstreamCluster --- FilterChain
@enduml
