@startuml

VirtualCluster - PhysicalCluster

VirtualCluster *--{ "n" VirtualBroker
PhysicalCluster *--{ "n" PhysicalBroker

VirtualBroker }-- EndPoint
VirtualCluster --- FilterChain
PhysicalCluster --- FilterChain
@enduml
